# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff78b4b5d2b52e17c2a130a803b53d06d9e86da44116491bc64c66987963dd31f60e2dd58ec5d301c70e4d37cd10e2ff525435f8ef89ddeb60ad06a5444ad497

test:
  secret_key_base: 3a93199bc5f2b866cae530d9a20f230d75f8fad22339bf22668ab044b7d1f2249caed3278d805faf9ae5f1dbc0ce6bdf4a19bd513cd062c6dc63056147d8c3eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
